//! FFI bindings to OSv kernel C APIs.
//!
//! Generated by bindgen from `wrapper.h`. The wrapper header
//! re-declares the C-visible subset of `osv/device.h` and
//! `osv/bio.h`, avoiding the C++ types that bindgen cannot
//! parse (mutex_t, waitqueue, boost::intrusive).
//!
//! `struct bio` is opaque on the Rust side. Use the
//! `osv_bio_*` accessor functions to read and write fields.

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
